branches:
- name: 1.x
  range: 1.x
  channel: 1.x
- name: 2.x
  range: 2.x
  channel: 2.x
- main
- name: development
  prerelease: alpha
  channel: alpha

plugins:
- - "@semantic-release/commit-analyzer"
  - preset: angular
    releaseRules:
    - scope: no-release
      release: false
    - type: build
      release: patch
    - type: chore
      release: patch
    - type: ci
      release: false
    - type: docs
      release: false
    - type: style
      release: patch
    - type: refactor
      release: patch
    - type: test
      release: patch
- - "@semantic-release/release-notes-generator"
- - "@semantic-release/npm"
- - "@semantic-release/github"
