import { type GetServerSideProps } from 'next';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { env } from 'next-runtime-env';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

type Props = {
  bar: string;
};

export default function ServerSide({ bar }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>BAR: {bar}</p>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  return {
    props: {
      bar: env('BAR'),
    },
  };
};
