name: Back-merge

description: Back-merge main into development.

inputs:
  gh_token:
    description: The Github token to use for authentication.
    required: true
  git_user_email:
    description: The email of the user to use for the git commit.
    required: true
  git_user_name:
    description: The name of the user to use for the git commit.
    required: true
  main_branch:
    description: The main branch to back-merge from.
    required: false
    default: "main"

runs:
  using: "composite"

  steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      token: ${{ inputs.gh_token }}

  - name: Setup git config
    shell: bash
    env:
      GIT_USER_EMAIL: ${{ inputs.git_user_email }}
      GIT_USER_NAME: ${{ inputs.git_user_name }}
    run: |
      git config --global user.email "${GIT_USER_EMAIL}"
      git config --global user.name "${GIT_USER_NAME}"

  - name: Merge main back to development
    shell: bash
    env:
      MAIN_BRANCH: ${{ inputs.main_branch }}
    run: |
      git fetch --unshallow
      git checkout development
      git pull
      git merge --no-ff "origin/${MAIN_BRANCH}" -m "ci: 🔀 back-merge ${MAIN_BRANCH} into development"
      git push
