name: Setup pnpm

description: Setup pnpm with caching and install dependencies.

inputs:
  npm_token:
    description: The npm token to use for authentication.
    required: true
  install_dependencies:
    description: Whether to install dependencies.
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
  - name: Install pnpm
    uses: pnpm/action-setup@v4
    id: pnpm-install
    with:
      version: 9
      run_install: false

  - name: Install Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v4
    with:
      node-version: ${{ matrix.node-version }}
      cache: pnpm
      registry-url: 'https://registry.npmjs.org'
    env:
      NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

  - name: Install dependencies
    shell: bash
    if: ${{ inputs.install_dependencies == 'true' }}
    run: |
      pnpm install --frozen-lockfile
